### ISSUE TITLE
Error in Train.py

### ISSUE THREAD

**Issue by multipm** [BoyuanJiang/Age-Gender-Estimate-TF#11]
Hi, very thanks for your project and you effort !!
Do you have any idea, why train.py doesn't work. ? I have tensorflow 1.4.0.

restore and continue training!
2018-04-09 12:23:47.425063: W D:\dump\tf\tf1.4-1\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: file_name (data type: string) is required but could not be found.

2018-04-09 12:23:49.061344: W D:\dump\tf\tf1.4-1\tensorflow\core\framework\op_kernel.cc:1192] Invalid argument: Name: <unknown>, Feature: file_name (data type: string) is required but could not be found.
Model saved in file: ./models\model.ckpt-0

Traceback (most recent call last):
  File "train.py", line 145, in <module>
    log_dir=args.log_path, start_lr=args.learning_rate, wd=args.weight_decay, kp=args.keep_prob)
  File "train.py", line 125, in run_training
    coord.join(threads)
  File "C:\Program Files\programovani\Python35\lib\site-packages\tensorflow\python\training\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "C:\Program Files\programovani\Python35\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files\programovani\Python35\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "C:\Program Files\programovani\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "C:\Program Files\programovani\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: <unknown>, Feature: file_name (data type: string) is required but could not be found.
         [[Node: input/ParseSingleExample/ParseExample/ParseExample = ParseExample[Ndense=4, Nsparse=0, Tdense=[DT_INT64, DT_STRING, DT_INT64, DT_STRING], dense_shapes=[[], [], [], []], sparse_types=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input/ParseSingleExample/ExpandDims, input/ParseSingleExample/ParseExample/ParseExample/names, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_0, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_1, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_2, input/ParseSingleExample/ParseExample/ParseExample/dense_keys_3, input/ParseSingleExample/ParseExample/Const, input/ParseSingleExample/ParseExample/ParseExample/names, input/ParseSingleExample/ParseExample/Const, input/ParseSingleExample/ParseExample/ParseExample/names)]]

**Comment by BoyuanJiang** [comment]
It seems that you are running on windows, for the error **tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Feature: file_name (data type: string) is required but could not be found.** I think that the tfrecords you make may some mistakes.
Run it on linux  if possible.

**Comment by mason1002** [comment]
> It seems that you are running on windows, for the error **tensorflow.python.framework.errors_impl.InvalidArgumentError: Name: , Feature: file_name (data type: string) is required but could not be found.** I think that the tfrecords you make may some mistakes.
> Run it on linux if possible.

I met exactly the same issue, and I ran on linux...
