### ISSUE TITLE
Issue running convert_to_records.py (and multiCPU).

### ISSUE THREAD

**Issue by EzieI** [BoyuanJiang/Age-Gender-Estimate-TF#13]
Hello, this is an amazing code, thank you for allowing us to view it. I'm attempting to convert the IMDB data set into records and I get the following error:

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "convert_to_records.py", line 188, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "convert_to_records.py", line 151, in main
    data_sets = get_meta('./data/imdb_crop/imdb.mat','imdb')
  File "convert_to_records.py", line 123, in get_meta
    meta = loadmat(mat_path)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

Additionally, if I wanted to run the convert_to_records.py on my GPU, would I use the syntax:

python convert_to_records.py --imdb --cuda

Thank you for your time!

**Comment by EzieI** [comment]
I had the directories wrong. I apologize for that.
